name: Tests

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:

jobs:
  test-gala:
    name: Gala
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Linux
        run: |
          sudo apt-get install gsl-bin libgsl0-dev

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"

      - name: Install Gala
        run: |
          pip install -v gala

      - name: Test import
        run: |
          python -c "import gala.potential as gp; pot = gp.PowerLawCutoffPotential(m=1.0, alpha=1.0, r_c=1.0); print(pot.energy([1.0, 0.0, 0.0]))"
          echo "Done"

  # test-skip:
  #   name: Nothin
  #   runs-on: "ubuntu-latest"
  #   if: ${{ ! contains(github.event.head_commit.message, '[skip tests]') }}
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Sup
  #       run: |
  #         echo "Testing"
